version: "3.9"

services:
  angular:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    depends_on:
      - symfony
    networks:
      - symfony 

  symfony:
    build: ./backend
    ports:
      - 8081:8081
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_URL=mysql://root:jardin@mysql:3306/jardin_actuel?serverVersion=8&charset=utf8mb4
    depends_on:
      - mysql
    networks:
      - symfony

  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=jardin_actuel
      - MYSQL_ROOT_PASSWORD=jardin
      - MYSQL_USER=jardin
      - MYSQL_PASSWORD=jardin

    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    networks:
      - symfony
    ports:
      - 3307:3306

  cypress:
    build: 
      context: .
      dockerfile: ./cypress/Dockerfile
    depends_on: 
      - angular
    command: npx cypress run
    environment:
      - CYPRESS_baseUrl=http://angular:8080
      - CYPRESS_username=test2@test.fr
      - CYPRESS_password=testtest
    networks:
      - symfony
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.config.js:/app/cypress.config.js

networks:
  symfony:
  
volumes:
  data:
